
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module multiplier #(parameter n = 32)(
    input [n-1:0] A, B,
	 input Clock,
	 input reset,
	 input start,
	 input mode,
	 output [n-1:0] Product,
	 output reg done
);

	wire sign1,sign2;
	wire [n-2:n-9] exp1,exp2;
	wire [n-10:0] frac1,frac2,tempFrac;
	wire [7:0] tempExp1,tempExp2;
	wire [6:0] fracHigh1, fracHigh2;
	wire [24:0] tempFrac1, tempFrac2;
	wire carry1;
	wire carry2;
	wire carry3;
	wire mMSB, tempSign;
	wire [49:0] tempOut;
	wire [8:0] fracHighMult1, fracHighMult2;
	wire [17:0] tempOut2;
	wire [22:0] tempmodeOut1; 
	wire [6:0]  tempmodeOut2;

	
	assign sign1 = A[31];
	assign sign2 = B[31];
	assign exp1  = A[30:23];
	assign exp2  = B[30:23];
	assign frac1 = A[22:0];
	assign frac2 = B[22:0];
	assign fracHigh1 = A[22:16];  
	assign fracHigh2 = B[22:16];
	
	assign tempSign = sign1 ^ sign2;
	
	RippleCarryAdder #(.n(8)) add1(exp1,exp2,tempExp1,carry1);
	
	RippleCarryAdder #(.n(8)) add2(tempExp1,8'b10000001,tempExp2,carry2);
	
	assign tempFrac1 = {2'b01,frac1};
	assign tempFrac2 = {2'b01,frac2};
	assign fracHighMult1 = {2'b01, fracHigh1};
	assign fracHighMult2 = {2'b01, fracHigh2};
	assign tempOut = tempFrac1 * tempFrac2;
        assign tempOut2 = fracHighMult1 * fracHighMult2;

	wire [7:0] tempExp;
	
	assign mMSB = ~mode ? tempOut[47] : tempOut2[15];
	
	RippleCarryAdder #(.n(8)) add3(tempExp2,{7'b0000000,mMSB},tempExp,carry3);
	
	assign tempmodeOut1 = tempOut[47] ? tempOut[46:24] : tempOut[45:23];
	assign tempmodeOut2 = tempOut2[15] ? tempOut2[14:8] : tempOut2[13:7];
	
	assign tempFrac = mode ? {tempmodeOut2, 16'b0000000000000000} : tempmodeOut1;
	
	assign Product ={tempSign,tempExp,{(~mode ? tempmodeOut1[22:16] : tempmodeOut2[6:0]),(~mode ? tempmodeOut1[15:0] : 16'b0000000000000000)}};
	
	
	
endmodule	





	
